name: Terraform S3 infra

on:
  push:
    branches: [ "main" ]
    paths:
      - "terraform/infra-s3/**"
      - ".github/workflows/terraform-s3.yml"
  pull_request:
    paths:
      - "terraform/infra-s3/**"
      - ".github/workflows/terraform-s3.yml"

env:
  AWS_REGION: eu-west-1
  # Terraform plukker automatisk opp TF_VAR_* som input-variabler.
  TF_VAR_aws_region: eu-west-1
  TF_VAR_bucket_name: ${{ secrets.SENTIMENT_BUCKET_NAME }}

jobs:
  tf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.7"

      - name: Terraform fmt (check)
        run: terraform fmt -check
        working-directory: terraform/infra-s3

      - name: Terraform init
        run: terraform init -input=false
        working-directory: terraform/infra-s3

      - name: Terraform validate
        run: terraform validate
        working-directory: terraform/infra-s3
