name: Terraform S3

on:
  push:
    branches:
      - main
    paths:
      - infra-s3/**
      - .github/workflows/terraform-s3.yml

jobs:
  tf:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1   # ‚Üê KORREKT REGION

      - uses: hashicorp/setup-terraform@v3

      - run: terraform fmt -check
        working-directory: infra-s3

      - run: terraform init
        working-directory: infra-s3

      - run: terraform validate
        working-directory: infra-s3

      - run: terraform plan
        working-directory: infra-s3

      - if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
        working-directory: infra-s3

